### ISSUE TITLE
Allow processing with missing balances for OFX

### ISSUE THREAD

**Issue by chase-dwelle** [redstreet/beancount_reds_importers#40]
I'm using Fidelity for most of my financial life. Part of that includes using their cash management account and a brokerage account that acts like a checking account.

I'm using the importers for the investment brokerage accounts just fine, but when I try to apply a `banking.Importer` for the more "bank"-like brokerage accounts I get the error that `InvestmentStatement object has no attribute 'balance'`. Traceback at the bottom. 

I tried creating a custom importer for the "banking" accounts with `self.include_balances = False` to skip adding balances, but still get the same error.

```
class Importer(banking.Importer, ofxreader.Importer):
    IMPORTER_NAME = "Fidelity Banking Accounts"

    def custom_init(self):
        if not self.custom_init_run:
            self.max_rounding_error = 0.04
            self.filename_pattern_def = "fidelity_banking*"
            self.includes_balances = False
            self.custom_init_run = True
```

`oft-summarize` works, but seems to leave the balance as `None`:
```
Statement info: 2022-12-01 00:00:00 -- 2022-12-29 00:00:00. Bal: []
```

I don't mind not having balance info for these accounts. Would it be acceptable to try and warn for this behavior, or is there something likely wrong with OFX file?

```
ERROR:root:Importer personal_finance.ingestors.beancount_reds_importers.fidelity_banking.Importer.extract() raised an unexpected error: 'InvestmentStatement' object has no attribute 'balance'
Traceback (most recent call last):
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/beancount/ingest/extract.py", line 182, in extract
    new_entries = extract_from_file(
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/beancount/ingest/extract.py", line 67, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/smart_importer/hooks.py", line 40, in patched_extract_method
    imported_entries = unpatched_extract(
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/beancount_reds_importers/libtransactionbuilder/banking.py", line 119, in extract
    new_entries += self.extract_balance(file, counter)
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/beancount_reds_importers/libtransactionbuilder/banking.py", line 67, in extract_balance
    for bal in self.get_balance_statement():
  File "~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/beancount_reds_importers/libreader/ofxreader.py", line 56, in get_balance_statement
    yield Balance(date, self.ofx_account.statement.balance)
AttributeError: 'InvestmentStatement' object has no attribute 'balance'
```

**Comment by chase-dwelle** [comment]
Closing because posted this in the wrong repo. Correct issue is here: https://github.com/redstreet/beancount_reds_plugins/issues/23

**Comment by redstreet** [comment]
ofxreader.py hardcodes `includes_balances` to `True` (it is not meant to be overridden). What we should do instead is to check if the ofx file supplies balances. Fix is above. Try it and let me know?

**Comment by chase-dwelle** [comment]
Thanks, the patch does work and that's good enough for me. Thanks!

I'm not that familiar with OFX, but below is what _seems_ like the balance information in the fetched OFX file, which seems to track with what's in `ofxparse` but maybe there's something I'm missing.

The import config, which works with the patch, is:

```python
apply_hooks(
        fidelity_banking.Importer(
            {
                "account_number": "1234567",
                "main_account": "Assets:Fidelity:CMA",
                "filename_pattern": "fidelity_banking_.*",
            }
        ),
        [PredictPostings()],
    ),
```


```xml
                <INVBAL>
                    <AVAILCASH>12345.67</AVAILCASH>
                    <MARGINBALANCE>+00000000000.00</MARGINBALANCE>
                    <SHORTBALANCE>+00000000000.00</SHORTBALANCE>
                    <BUYPOWER>+00000000000.00</BUYPOWER>
                    <BALLIST>
                        <BAL>
                            <NAME>Networth</NAME>
                            <DESC>The net market value of all long and short positions in the
                                account</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>12345.67</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Margin Equity</NAME>
                            <DESC>The margin market value less any margin debit balance</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Margin Equity Percentage</NAME>
                            <DESC>Margin equity / market value of long and short positions</DESC>
                            <BALTYPE>PERCENT</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Cash Debit Balance</NAME>
                            <DESC>Cash Debit Balance</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Total Money Markets</NAME>
                            <DESC>The total value of all money market positions in the cash account</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>12345.67</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>House Surplus</NAME>
                            <DESC>Equity amount above house requirements</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>NYSE Surplus</NAME>
                            <DESC>Equity amount above exchange requirements</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Federal Surplus</NAME>
                            <DESC>Amount above federal requirements</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Buying Power - Equities</NAME>
                            <DESC>Amount of equities you can buy on margin without generating a
                                margin call</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Buying Power - Municipal Bonds</NAME>
                            <DESC>Amount of municipal bonds you can buy on margin without generating
                                a margin call</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Buying Power - Government Bonds</NAME>
                            <DESC>Amount of government bonds you can buy on margin without
                                generating a margin cal</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Buying Power - Corporate Bonds</NAME>
                            <DESC>Amount you can buy of corporate bonds on margin with no margin
                                call</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Option Market Value</NAME>
                            <DESC>The market value of all options in the account</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Option In The Money Amount</NAME>
                            <DESC>The in-the-money amount on covered options</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Cash Market value</NAME>
                            <DESC>Total value of all cash account positions</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Margin Market Value</NAME>
                            <DESC>Total value of positions in margin less in-the-money amount of
                                covered options</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Short Market Value</NAME>
                            <DESC>Total value of short positions less in-the-money amount of covered
                                put options</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                        <BAL>
                            <NAME>Available to Borrow</NAME>
                            <DESC>Cash amount that can be borrowed without generating a margin call</DESC>
                            <BALTYPE>DOLLAR</BALTYPE>
                            <VALUE>0.0</VALUE>
                            <DTASOF>20221230033014.000[-5:EST]</DTASOF>
                            <CURRENCY>
                                <CURRATE>1.000</CURRATE>
                                <CURSYM>USD</CURSYM>
                            </CURRENCY>
                        </BAL>
                    </BALLIST>
                </INVBAL>
```

**Comment by redstreet** [comment]
Great!

Thanks for the ofx snippet. That does look like balance info. I don't know why ofx-summarize or the impoter don't see it.

If you could attach the entire ofx file, I can take a look. Anonymized, of course. It's no big deal if it's too much pain.

**Comment by chase-dwelle** [comment]
Thanks, here's a [gist with a stripped-down OFX file](https://gist.github.com/chase-dwelle/3401fd1f79ebb4692e3e4de707e9614b):

One interesting thing to note that may be related. When I use `ofx-summarize` I get the following output. Not sure if the XML parsing warning is worth paying attention to, but one thing to note is that there are 10 transactions in the file but only five show up using `ofx-summarize`. 

```
~/pypoetry/virtualenvs/personal-finance-Iy5H7pvA-py3.9/lib/python3.9/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(
Total number of accounts: 1
----------------
Account info:   X12345678 fidelity.com
Statement info: 2022-12-22 00:00:00 -- 2022-12-31 00:00:00. Bal: []
Types:  {'other', 'dep', 'income'}

2022-12-30 05:00:00 income DIVIDEND RECEIVED 100.4100
2022-12-30 05:00:00 other TRANSFERRED TO ACCT 1 TRANSFERRED TO ACCT 1 -5000.0000
2022-12-29 05:00:00 dep CHECK RECEIVED CHECK RECEIVED 250.0000
2022-12-29 05:00:00 dep CHECK RECEIVED CHECK RECEIVED 250.0000
2022-12-29 05:00:00 dep CHECK RECEIVED CHECK RECEIVED 250.0000

```

**Comment by redstreet** [comment]
> Thanks, here's a [gist with a stripped-down OFX file](https://gist.github.com/chase-dwelle/3401fd1f79ebb4692e3e4de707e9614b).

Great! I'll take a look soon.

> Also it appears that with the patch outputting of balances no longer works with `bean-extract`. Would be interested to know if you get the same result. If not, perhaps it's a dependency issue on my end.

Hmm, not sure I understood. What is the combination of {importer, transaction_builder, ofx_file} that fails to produce the balance entries that you expect?

 
> One interesting thing to note that may be related. When I use `ofx-summarize` I get the following output. Not sure if the XML parsing warning is worth paying attention to, but one thing to note is that there are 10 transactions in the file but only five show up using `ofx-summarize`.

Did you try '-n 1000'? Also `ofx-summarize --help`

XML warning: might be a different version in one of the dependencies, I'm not seeing that so far.

**Comment by redstreet** [comment]
I'm seeing the `XMLParsedAsHTMLWarning` as well now. See:
https://github.com/jseutter/ofxparse/issues/170
https://github.com/jseutter/ofxparse/pull/108

I'm not sure I understand why this hasn't been fixed in `ofxparse`, but I will filter out this warning.
