### ISSUE TITLE
Vanguard unknown entity type error when dealing with CDs

### ISSUE THREAD

**Issue by kklipsch** [redstreet/beancount_reds_importers#75]
When running an import on a vanguard ofx document that has CDs in it I get

ERROR:root:Importer beancount_reds_importers.vanguard.Importer.extract() raised an unexpected error: Unknown entry type
Traceback (most recent call last):
  File "/Users/kaseyklipsch/pf/.venv/lib/python3.11/site-packages/beancount/ingest/extract.py", line 182, in extract
    new_entries = extract_from_file(
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/kaseyklipsch/pf/.venv/lib/python3.11/site-packages/beancount/ingest/extract.py", line 67, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaseyklipsch/pf/.venv/lib/python3.11/site-packages/beancount_reds_importers/libtransactionbuilder/investments.py", line 423, in extract
    new_entries += self.extract_transactions(file, counter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaseyklipsch/pf/.venv/lib/python3.11/site-packages/beancount_reds_importers/libtransactionbuilder/investments.py", line 351, in extract_transactions
    raise Exception('Unknown entry type')

An example line:
<BUYDEBT><INVBUY><INVTRAN><FITID>206889464</FITID><DTTRADE>20230613160000.000[-5:EST]</DTTRADE><DTSETTLE>20230615160000.000[-5:EST]</DTSETTLE><MEMO>BUY</MEMO></INVTRAN><SECID><UNIQUEID>02007GP98</UNIQUEID><UNIQUEIDTYPE>CUSIP</UNIQUEIDTYPE></SECID><UNITS>20000.0</UNITS><UNITPRICE>100.0</UNITPRICE><TOTAL>-20000.0</TOTAL><SUBACCTSEC>CASH</SUBACCTSEC><SUBACCTFUND>CASH</SUBACCTFUND></INVBUY><ACCRDINT>0.0</ACCRDINT></BUYDEBT>

**Comment by redstreet** [comment]
Hi, thanks for filling!

This should be an easy fix, likely just adding the type to the right place in the importer, and adding the unit test.

Would you be up for taking a stab at a fix? Do let me know. Thanks!

**Comment by kklipsch** [comment]
I can take a shot.  I'm not a python programmer so some of the idioms are not clear to me.  It seems like entities are hard coded at least 2 places: https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/libtransactionbuilder/investments.py#L366-L379 and https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/libtransactionbuilder/investments.py#L102-L126

So it doesn't seem like its just a vanguard importer issue.  The tests though are defined at the financial institution level it seems?

So i guess do I just add the new entity type to the transaction builder library and then test it at the vanguard level?

**Comment by redstreet** [comment]
All of that is exactly right :). If you'd like to to this, I'd recommend starting with testing by coping the of files [here](https://github.com/redstreet/beancount_reds_importers/tree/main/beancount_reds_importers/importers/vanguard/tests) to a set with a new name, and running `pytest` in that directory.

Alternatively, you're also welcome to simply send me an anonymized, valid `.ofx` file with the case that fails, and the expected output (the Beancount transaction), and I'll fix it. This might be the easier route than learning a hundred python things at once :).

**Comment by kklipsch** [comment]
Sorry I haven't gotten to this.  I tried a few times to figure out how to get going on the code base.  I think I'm close but probably won't get back to this issue for a few months.

**Comment by redstreet** [comment]
No worries, thanks for the note! From above:

> you're welcome to simply send me an anonymized, valid .ofx file with the case that fails, and the expected output (the Beancount transaction), and I'll fix it.
